<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rufus.Cli\Rufus.Cli.csproj" />
    <ProjectReference Include="..\..\src\Rufus.RCK.Core\Rufus.RCK.Core.csproj" />
  </ItemGroup>
</Project>
